### ISSUE TITLE
assigning value to token.owner: only executes once

### ISSUE THREAD

**Issue by alinobrasil** [marcusrein/FDS-Workshop-Repo-2023#2]
In the mapping file `beanz.ts`, the value of `token.owner` is assigned like this: 
```
token.owner = event.params.to.toHexString();
```

This is currently happening inside the ```if (!token) ``` block, so this will assign the owner the first time a token appears in Transfer events. 
But it won't update the owner in any subsequent Transfer events. 

Should move line outside of the ```if (!token) ``` block, just before saving the token entity.

**Comment by marcusrein** [comment]
Great catch, thank you!
